- src/main/java/com/nci/automation/web/CommonUtils.java
- src/main/java/com/nci/automation/web/JavascriptUtils.java
- src/main/resources/conf/env/dev2.xml
- src/main/resources/conf/env/test.xml
- src/test/java/ServiceNow/CHARMS/Features/RasopathyStudy/RAS Entire Flow.feature
- src/test/java/ServiceNow/CHARMS/Pages/NativeViewCHARMSParticipantConsentPage.java
- src/test/java/ServiceNow/CHARMS/Pages/NativeViewCHARMSParticipantDetailsPage.java
- src/test/java/ServiceNow/CHARMS/Pages/ParticipantDetailsPage.java
- src/test/java/ServiceNow/CHARMS/Pages/TestAccountResetPage.java
- src/test/java/ServiceNow/CHARMS/StepsImplementation/RasScenario1StepsImpl.java
- src/test/java/ServiceNow/CHARMS/StepsImplementation/RasScenario2StepsImpl.java
- src/test/java/ServiceNow/CHARMS/StepsImplementation/RasScenario3StepsImpl.java
- src/test/java/ServiceNow/CHARMS/StepsImplementation/RasScenario4StepsImpl.java
- src/test/java/ServiceNow/CHARMS/StepsImplementation/TestAccountResetImpl.java
- src/test/java/ServiceNow/SandBoxUpgradeTest/Steps/TestSteps.java
- src/test/java/appsCommon/Pages/NativeViewHomePage.java
- src/test/java/appsCommon/Utils/ServiceNow_Common_Methods.java
- Updated CHARMS Test Automation
> dev2 upgrade

- src/main/java/com/nci/automation/web/CommonUtils.java
- src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Steps/ApplicantProfileSteps.java
- src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/StepsImplementation/ApplicantProfileStepsImpl.java
Added common method that allows user to format a phone number.
Updated assertions for SSJ Verify the Save application functionality scenario
> Phone formatting method & Phone assertions added

- src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Features/Applicant Profile.feature
- src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Features/OWM_Vacancy_Manager.feature
- src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Steps/ApplicantProfileSteps.java
- src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/StepsImplementation/ApplicantProfileStepsImpl.java
- src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/Features/Applicant Flow.feature
- src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/Steps/ApplicantFlowSteps.java
Fixed smoke tests logic for Saving Demographics functionality after bug fix
> Fixed smoke tests logic for Saving Demographics functionality after bug fix

- src/test/java/ServiceNow/CHARMS/Features/RasopathyStudy/RAS Consent Scenarios.feature
- src/test/java/ServiceNow/CHARMS/Pages/CGBIIQPage.java
- src/test/java/ServiceNow/CHARMS/Steps/RAS_All_Steps.java
- src/test/java/ServiceNow/CHARMS/Steps/RAS_Common_Methods.java
- src/test/java/ServiceNow/CHARMS/StepsImplementation/RASStudy/RAS_Screener_Submissions_StepsImpl.java
Verifying that a Download Study Consent widget shows on portal and when clicked downloads the most recent Consent Record.
> CHARMS RAS @CP2-3603 Verifying that a Download Study Consent widget shows on portal and when clicked downloads the most recent Consent Record.

- src/test/java/ServiceNow/ESR/Playwright/Features/ESRNotification.feature
- src/test/java/ServiceNow/ESR/Playwright/Features/ESRShortDescription.feature
- src/test/java/ServiceNow/ESR/Playwright/Pages/CreateESRPage.java
- src/test/java/ServiceNow/ESR/Playwright/Steps/ESRNotificationSteps.java
- src/test/java/ServiceNow/ESR/Playwright/Steps/ESRShortDescriptionSteps.java
- src/test/java/ServiceNow/ESR/Playwright/StepsImplementation/CreateESRPageStepsImplementation.java
- src/test/java/ServiceNow/ESR/Playwright/StepsImplementation/ESRNotificationStepsImplementation.java
- src/test/java/ServiceNow/ESR/Playwright/StepsImplementation/ESRShortDescriptionStepsImplementation.java
> ESR Notifications and Short Description fields

- src/main/java/com/nci/automation/web/TestProperties.java
- src/test/java/CustomBusiness/Egrants/Features/EgrantsLinksVerificationAndManagementMenu.feature
- src/test/java/CustomBusiness/Egrants/Pages/EgrantsQuickLinkAndManagementMenuPage.java
- src/test/java/CustomBusiness/Egrants/Steps/QuickLinkVerificationAndManagementMenuSteps.java
- src/test/java/CustomBusiness/Egrants/StepsImplementation/EgrantsStepImplementation.java
- src/test/java/CustomBusiness/Egrants/Utils/Egrants_Constants.java
These are old requirements hence there are no Story Ids associated to them.
> eGrants - Add and remove flag maintenance for a grant year

- src/test/java/CustomBusiness/Egrants/Features/EgrantsLinksVerificationAndManagementMenu.feature
- src/test/java/CustomBusiness/Egrants/Pages/EgrantsQuickLinkAndManagementMenuPage.java
- src/test/java/CustomBusiness/Egrants/Steps/QuickLinkVerificationAndManagementMenuSteps.java
- src/test/java/CustomBusiness/Egrants/Utils/Egrants_CommonUtils.java
- src/test/java/CustomBusiness/Egrants/Utils/Egrants_Constants.java
> EGRANTS - Add a new user and verify system restricts adding an existing user

- src/test/java/CustomBusiness/Egrants/Features/EgrantsSearchAndFileManagementScenarios.feature
- src/test/java/CustomBusiness/Egrants/Pages/EgrantsSearchAndFileManagementScenariosPage.java
- src/test/java/CustomBusiness/Egrants/Steps/EgrantsSearchAndFileManagementSteps.java
- src/test/java/CustomBusiness/Egrants/Utils/Egrants_CommonUtils.java
These are old requirements, hence there are no Jira user Ids for them.
> eGrants - Add funding document and Move supplement application

- src/main/java/com/nci/automation/web/TestProperties.java
- src/test/java/ServiceNow/AwardNomination/Constants/AwardNominationConstants.java
- src/test/java/ServiceNow/AwardNomination/Features/VIBEAppreciationRequest.feature
- src/test/java/ServiceNow/AwardNomination/Pages/AwardNominationPage.java
- src/test/java/ServiceNow/AwardNomination/Steps/AwardNominationSteps.java
- src/test/java/ServiceNow/AwardNomination/StepsImplementation/AwardNominationStepsImplementation.java
- src/test/java/ServiceNow/ServiceNowRunners/AwardNominationRunners/AwardNominationProgressionRunner.java
- src/test/java/ServiceNow/ServiceNowRunners/AwardNominationRunners/AwardNominationRegressionRunner.java
- src/test/java/ServiceNow/ServiceNowRunners/AwardNominationRunners/AwardNominationSmokeRunner.java
- src/test/java/appsCommon/PageInitializers/PageInitializer.java
Submit Award Nomination request
> Submit Award Nomination request

- src/main/java/com/nci/automation/utils/ExcelReader.java
- src/test/java/CHARMS/Constants/CHARMS_Data_File_Path_Constants.java
- src/test/java/CHARMS/Features/FHQ/FHQAuntUncleRecordProducer.feature
- src/test/java/CHARMS/Features/FHQ/FHQChildRecordProducer.feature
- src/test/java/CHARMS/Features/FHQ/FHQGrandChildrenRecordProducer.feature
- src/test/java/CHARMS/Features/FHQ/FHQGrandParentRecordProducer.feature
- src/test/java/CHARMS/Features/FHQ/FHQNieceNephewRecordProducer.feature
- src/test/java/CHARMS/Features/FHQ/FHQParentRecordProducer.feature
- src/test/java/CHARMS/Features/FHQ/FHQPartnerRecordProducer.feature
- src/test/java/CHARMS/Features/FHQ/FHQPatientPersonalRecordProducer.feature
- src/test/java/CHARMS/Features/FHQ/FHQRecordProducersNativeView.feature
- src/test/java/CHARMS/Features/FHQ/FHQRegression.feature
- src/test/java/CHARMS/Features/FHQ/FHQSiblingRecordProducer.feature
- src/test/java/CHARMS/Features/FHQ/FHQSubmission.feature
- src/test/java/CHARMS/Features/FanconiStudy/FanconiEligibilityQuestionnaire.feature
- src/test/java/CHARMS/Features/IIQ/IIQ Submission.feature
- src/test/java/CHARMS/Features/MelanomaStudy/Melanoma_Screener_Scenarios.feature
- src/test/java/CHARMS/Features/RasopathyStudy/RAS Survey Data Verification.feature
- src/test/java/CHARMS/Runners/RunCHARMSFHQRegressionTest.java
- src/test/java/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
- src/test/java/CHARMS/StepsImplementation/RASStudy/RASSurveyStepsImpl.java
- src/test/java/CHARMS/StepsImplementation/RASSurveyStepsImpl.java
- src/test/java/CHARMS/Utils/CharmsUtil.java
Added the deleted files back to charms folder
> Added the deleted files back to charms folder

- src/test/java/ANALYSIS_TOOLS/JPSurv/features/JPSurvHomePagePlaywright.feature
- src/test/java/ANALYSIS_TOOLS/JPSurv/pages/JPSurvHomePagePlaywright.java
- src/test/java/ANALYSIS_TOOLS/JPSurv/steps/JPSurvHomePagePlaywrightSteps.java
- src/test/java/ANALYSIS_TOOLS/JPSurv/stepsImplementations/JPSurvHomePagePlaywrightStepImp.java
Analysis Tools - Implemented 2 test cases JPSURV Application
> Analysis Tools - Implemented 2 test cases JPSURV Application

- src/test/java/ANALYSIS_TOOLS/JPSurv/features/JPSurvHomePagePlaywright.feature
- src/test/java/ANALYSIS_TOOLS/JPSurv/pages/JPSurvHomePagePlaywright.java
- src/test/java/ANALYSIS_TOOLS/JPSurv/steps/JPSurvHomePagePlaywrightSteps.java
- src/test/java/ANALYSIS_TOOLS/JPSurv/stepsImplementations/JPSurvHomePagePlaywrightStepImp.java
- src/test/java/ANALYSIS_TOOLS/JPSurv/utils/JPSurvConstants.java
Analysis Tools - Implemented 3 test cases JPSURV Application
> Analysis Tools - Implemented 3 test cases JPSURV Application 

- .gitignore
- src/main/java/com/nci/automation/web/TestProperties.java
- src/test/java/CUSTOM_BUSINESS/Egrants/features/EgrantsLinksVerificationAndManagementMenu.feature
- src/test/java/CUSTOM_BUSINESS/Oasys/Features/Contracts.feature
- src/test/java/CUSTOM_BUSINESS/Oasys/Pages/I_Trust_Page.java
- src/test/java/CUSTOM_BUSINESS/Oasys/Steps/Contracts.java
- src/test/java/CUSTOM_BUSINESS/Oasys/StepsImplementation/Oasys_Steps_Implementation.java
- src/test/java/CUSTOM_BUSINESS/Oasys/runners/RunOasysRegressionTest.java
These are old requirements, hence there are no Jira Story Ids available for them.
> OASYS - Edit contract information and assignment

- src/test/java/CUSTOM_BUSINESS/OASYS/Features/Contracts.feature
- src/test/java/CUSTOM_BUSINESS/OASYS/Steps/Contracts.java
- src/test/java/CUSTOM_BUSINESS/OASYS/Utils/OASYS_Constants.java
> Import a contract and verify search filters

- src/test/java/ANALYSIS_TOOLS/JPSurv/features/JPSurvHomePagePlaywright.feature
- src/test/java/ANALYSIS_TOOLS/JPSurv/pages/JPSurvHomePagePlaywright.java
- src/test/java/ANALYSIS_TOOLS/JPSurv/stepsImplementations/JPSurvHomePagePlaywrightStepImp.java
Analysis Tools - Implemented 6 test cases JPSURV Application 
> Analysis Tools - Implemented 6 test cases JPSURV Application 

- src/test/java/CUSTOM_BUSINESS/OASYS/Features/Invoice_Page.feature
- src/test/java/CUSTOM_BUSINESS/OASYS/Steps/Invoice_Page.java
- src/test/java/CUSTOM_BUSINESS/OASYS/Utils/OASYS_CommonUtils.java
- src/test/java/CUSTOM_BUSINESS/OASYS/Utils/OASYS_Constants.java
> OASYS - Submit an invoice & Assign additional reviewers

- .github/workflows/CUSTOM BUSINESS (.NET) - OASYS  Regression.yml
- src/test/java/CUSTOM_BUSINESS/OASYS/Steps/Invoice_Page.java
- src/test/java/CUSTOM_BUSINESS/OASYS/Utils/OASYS_CommonUtils.java
- src/test/java/CUSTOM_BUSINESS/OASYS/features/Invoice_Page.feature
> OASYS - Review an invoice as final approver & Delete an invoice

- .github/workflows/ANALYSIS TOOLS - ACT24 Regression.yml
- .github/workflows/ANALYSIS TOOLS - FORGEdb Regression.yml
- .github/workflows/ANALYSIS TOOLS - JPSurv Regression.yml
- .github/workflows/ANALYSIS TOOLS - MRAT Regression.yml
- .github/workflows/ANALYSIS TOOLS -BCRAT Regression.yml
Analysis Tools- Github Actions job Scheduled for ACT24 And JPSURV
> Analysis Tools- Github Actions job Scheduled for ACT24 And JPSURV 

- src/test/java/CUSTOM_BUSINESS/OASYS/Steps/Invoice_Page.java
- src/test/java/CUSTOM_BUSINESS/OASYS/features/Invoice_Page.feature
> OASYS - Invoice search filters and export results

- src/main/java/com/nci/automation/web/TestProperties.java
- src/test/java/ANALYSIS_TOOLS/CCRAT/playwright/features/CCRAT.feature
- src/test/java/ANALYSIS_TOOLS/CCRAT/playwright/steps/CCRAT_Steps.java
- src/test/java/ANALYSIS_TOOLS/CCRAT/playwright/stepsImplementation/CCRATStepsImpl.java
- src/test/java/ANALYSIS_TOOLS/CometsAnalytics/features/CometsAnalytics.feature
- src/test/java/ANALYSIS_TOOLS/CometsAnalytics/pages/CometsAnalyticsPage.java
- src/test/java/ANALYSIS_TOOLS/CometsAnalytics/runners/RunCometsAnalyticsProgressionTest.java
- src/test/java/ANALYSIS_TOOLS/CometsAnalytics/runners/RunCometsAnalyticsRegressionTest.java
- src/test/java/ANALYSIS_TOOLS/CometsAnalytics/runners/RunCometsAnalyticsSmokeTest.java
- src/test/java/ANALYSIS_TOOLS/CometsAnalytics/steps/CometsAnalyticsSteps.java
- src/test/java/ANALYSIS_TOOLS/CometsAnalytics/stepsImplementation/CometsAnalyticsStepImp.java
- src/test/java/ANALYSIS_TOOLS/CometsAnalytics/utils/CometsAnalysis_Constants.java
Analysis Tools-Implemented 5 test cases for  CometsAnalysis Application
> Analysis Tools-Implemented 5 test cases for  CometsAnalysis Application

- src/main/java/com/nci/automation/web/TestProperties.java
- src/test/java/APPS_COMMON/Pages/Playwright_Common_Locators.java
- src/test/java/PLATFORM_BUSINESS/NERD/playwright/Steps/Top_Accomplishment_New_Submission_Steps.java
NERD - Stored iframe as a String in Playwright_Common_Locators and imported static constant in NERD steps class
> NERD - Stored iframe as a String in Playwright_Common_Locators and imported static constant in NERD steps class

- src/test/java/ANALYSIS_TOOLS/mSigPortal/playwright/features/mSigPortalExploration.feature
- src/test/java/ANALYSIS_TOOLS/mSigPortal/playwright/features/mSigPortalHome.feature
- src/test/java/ANALYSIS_TOOLS/mSigPortal/playwright/features/mSigPortalVisualization.feature
- src/test/java/ANALYSIS_TOOLS/mSigPortal/playwright/pages/mSigPortalHomePage.java
- src/test/java/ANALYSIS_TOOLS/mSigPortal/playwright/steps/mSigPortalExploration_Steps.java
- src/test/java/ANALYSIS_TOOLS/mSigPortal/playwright/steps/mSigPortalHome_Steps.java
- src/test/java/ANALYSIS_TOOLS/mSigPortal/playwright/steps/mSigPortalVisualization_Steps.java
- src/test/java/ANALYSIS_TOOLS/mSigPortal/playwright/stepsImplementations/mSigPortalExplorationStepsImpl.java
- src/test/java/ANALYSIS_TOOLS/mSigPortal/playwright/stepsImplementations/mSigPortalHomeStepsImpl.java
- src/test/java/ANALYSIS_TOOLS/mSigPortal/playwright/stepsImplementations/mSigPortalVisualizationStepsImpl.java
- src/test/java/ANALYSIS_TOOLS/mSigPortal/playwright/utils/mSigPortalHome_Constants.java
- src/test/java/ANALYSIS_TOOLS/mSigPortal/runners/RunMSigPortalRegressionTest.java
Analysis Tools - Implemented 8 test cases for the mSigPortal
> Analysis Tools - Implemented 8 test cases for the mSigPortal 

- src/test/java/CUSTOM_BUSINESS/MRS/Steps/RequestForm.java
- src/test/java/CUSTOM_BUSINESS/MRS/features/RequestForm.feature
> MRS - Submit a request form for yourself

- pom.xml
- src/test/java/CHARMS/constants/MetforminScreenerConstants.java
- src/test/java/CHARMS/stepsImplementation/MetforminScreenerStepsImpl.java
Added new version in pom.xml for commons-io
> Added new version in pom.xml for commons-io

- src/test/java/CUSTOM_BUSINESS/MRS/Steps/RequestForm.java
- src/test/java/CUSTOM_BUSINESS/MRS/Utils/MRS_Constants.java
- src/test/java/CUSTOM_BUSINESS/MRS/features/RequestForm.feature
> MRS - Withdraw and disapprove a request
